[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Work"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    parent = "work"
    weight = 1

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "work"
    weight = 2

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 4

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    parent = "writing"
    weight = 4

[[main]]
    identifier = "Engineering"
    name = "Engineering"
    url = "/Engineering/"
    #url = "/posts/Engineering/" # Remove url param from Engineering/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 5

[[main]]
    identifier = "Philosophy"
    name = "Philosophy"
    url = "/Philosophy/"
    # url = "/posts/Philosophy/" # Remove url param from Engineering/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 5

[[main]]
    identifier = "Data Structures & Algorithms"
    name = "Data Structures & Algorithms"
    url = "/series/Data Structures & Algorithms"
    # url = "/posts/Data Structures & Algorithms/" # Remove url param from Engineering/_index.md frontmatter to use full permalink
    parent = "Learn"
    weight = 5

[[main]]
    identifier = "C++"
    name = "C++"
    url = "/series/C++"
    # url = "/posts/Data Structures & Algorithms/" # Remove url param from Engineering/_index.md frontmatter to use full permalink
    parent = "Learn"
    weight = 5

[[main]]
    identifier = "Machine Learning"
    name = "Machine Learning"
    url = "/series/Machine Learning"
    # url = "/posts/Data Structures & Algorithms/" # Remove url param from Engineering/_index.md frontmatter to use full permalink
    parent = "Learn"
    weight = 5


[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "explore"
    weight = 8

[[main]]
    identifier = "project-type"
    name = "Project Types"
    url = "/project-types/"
    parent = "explore"
    weight = 9